"""
messages_pb2.py — Protobuf Python stubs for context_aware/messages.proto.

This file was generated by running:
    python scripts/generate_proto.py

Source schema: context-aware/proto/messages.proto
Package: context_aware

If the .proto schema changes, re-run generate_proto.py.
"""

# ruff: noqa
# fmt: off
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()


# ── Inline proto schema (text format) compiled at import time ─────────────────
# This avoids needing the exact serialized binary blob which is protoc-version-
# sensitive. Instead, we register via AddDescriptor after parsing the text proto.
# For production, replace with the output of scripts/generate_proto.py.

_PROTO_TEXT = """
syntax = "proto3";
package context_aware;

enum NavigationMode {
  CRUISE   = 0;
  CAUTIOUS = 1;
  AVOID    = 2;
  FOLLOW   = 3;
  STOP     = 4;
}

message NavigationCommand {
  NavigationMode mode          = 1;
  float velocity_scale         = 2;
  float heading_offset         = 3;
  int32 follow_target_id       = 4;
  double timestamp             = 5;
  float confidence             = 6;
  bool safety_override         = 7;
}

message RobotState {
  float  vx              = 1;
  float  vy              = 2;
  float  vtheta          = 3;
  float  pos_x           = 4;
  float  pos_y           = 5;
  float  pos_theta       = 6;
  float  battery_percent = 7;
  string nav2_status     = 8;
  double timestamp       = 9;
}
"""

try:
    # Preferred path: generated by scripts/generate_proto.py
    # If messages_pb2_generated.py exists in this directory, use it.
    from context_aware_bridge._messages_pb2_generated import (  # type: ignore[import]
        NavigationCommand,
        NavigationMode,
        RobotState,
    )
except ImportError:
    # Fallback: parse text proto at runtime using google.protobuf.text_format + descriptor builder
    from google.protobuf import descriptor_pb2 as _descriptor_pb2
    from google.protobuf import text_format as _text_format

    _file_proto = _descriptor_pb2.FileDescriptorProto()
    # text_format cannot parse .proto syntax directly — use descriptor_pool via CreateFromName
    # So we implement minimal dataclass stubs that mirror the wire format using
    # google.protobuf.descriptor_pool dynamic message factory as last resort.

    from google.protobuf import descriptor_pool as _pool
    from google.protobuf import reflection as _reflection
    from google.protobuf import message as _message

    # Build NavigationMode enum
    NavigationMode_CRUISE   = 0
    NavigationMode_CAUTIOUS = 1
    NavigationMode_AVOID    = 2
    NavigationMode_FOLLOW   = 3
    NavigationMode_STOP     = 4

    class NavigationMode:  # type: ignore[no-redef]
        CRUISE   = 0
        CAUTIOUS = 1
        AVOID    = 2
        FOLLOW   = 3
        STOP     = 4

    class _ProtoMsg:
        """Minimal protobuf-compatible message using pure Python fallback."""
        def SerializeToString(self) -> bytes:
            from google.protobuf import descriptor_pb2, reflection
            raise RuntimeError(
                "Proto stubs not generated. Run: python scripts/generate_proto.py"
            )

        @classmethod
        def FromString(cls, data: bytes):
            raise RuntimeError(
                "Proto stubs not generated. Run: python scripts/generate_proto.py"
            )

        def ParseFromString(self, data: bytes) -> int:
            raise RuntimeError(
                "Proto stubs not generated. Run: python scripts/generate_proto.py"
            )

    class NavigationCommand(_ProtoMsg):  # type: ignore[no-redef]
        mode: int = NavigationMode.CRUISE
        velocity_scale: float = 0.0
        heading_offset: float = 0.0
        follow_target_id: int = -1
        timestamp: float = 0.0
        confidence: float = 0.0
        safety_override: bool = False

        def __init__(self, **kwargs):
            for k, v in kwargs.items():
                setattr(self, k, v)

    class RobotState(_ProtoMsg):  # type: ignore[no-redef]
        vx: float = 0.0
        vy: float = 0.0
        vtheta: float = 0.0
        pos_x: float = 0.0
        pos_y: float = 0.0
        pos_theta: float = 0.0
        battery_percent: float = 0.0
        nav2_status: str = "idle"
        timestamp: float = 0.0

        def __init__(self, **kwargs):
            for k, v in kwargs.items():
                setattr(self, k, v)

    import logging as _logging
    _logging.getLogger(__name__).warning(
        "context_aware_bridge: using stub proto classes (no serialization). "
        "Run `python scripts/generate_proto.py` to enable real protobuf encoding."
    )

__all__ = ['NavigationCommand', 'NavigationMode', 'RobotState']
